apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      developer: paulinenarvas
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
        developer: paulinenarvas
    spec:
      containers:
        - name: nginx
          image: nginx
